workflows:
  ios-workflow:
    name: iOS Build

    environment:
      node: latest
      xcode: latest

    scripts:
      - npm ci
      - npm install @capacitor/core @capacitor/cli

      # تجهيز Capacitor
      - npx cap sync ios

      # الدخول لمشروع iOS
      - cd ios/App

      # Build فعلي (ده المهم اللي كان ناقص عندك)
      - xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos build

      - cd ../..

    artifacts:
      - ios/App/build/**/*.app 
