workflows:
  ios-workflow:
    name: iOS Build

    environment:
      node: 18

    scripts:
      - npm install
      - npm install @capacitor/core @capacitor/cli

      # ❌ نشيل cap sync خالص من السيرفر

    artifacts:
      - ios/App/build/ios/ipa/*.ipa